DIRECTORY:
  dataset: D:/study/_data/AIconnect/test/test/images
  sample_submission_path : D:/study/_data/AIconnect/test/test/sample_submission.csv

TRAIN:
  train_serial: #'20230706_164725'
  batch_size: 32

PREDICT:
  seed: 42
  gpu: 0